export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    REFRESH: "/api/v1/auth/refresh",
    LOGOUT: "/api/v1/auth/logout",
  },
  METRICS: {
    GET_METRICS_PROFILES: "/api/v1/metrics/profiles",
    SYNC_METRICS_COUNTERS: "/api/v1/metrics/metrics-counters/sync",
    GET_METRICS_COUNTERS: "/api/v1/metrics/metrics-counters",
    GET_METRICS_COUNTER_OPTIONS: "/api/v1/metrics/metrics-counters/options",
    CREATE_METRICS_COUNTER: "/api/v1/metrics/metrics-counters",
    GET_METRICS_COUNTER_IMPORT_JOB_STATUS: (jobId: string) => `/api/v1/metrics/counter-import-jobs/${jobId}/status`,
    CREATE_METRICS_COUNTER_IMPORT: "/api/v1/metrics/counter-imports",
    GET_METRICS_COUNTER_IMPORTS: "/api/v1/metrics/counter-imports",
    UPDATE_METRICS_COUNTER_IMPORT: (importId: string) => `/api/v1/metrics/counter-imports/${importId}`,
    DELETE_METRICS_COUNTER_IMPORT: (importId: string) => `/api/v1/metrics/counter-imports/${importId}`,
    GET_METRICS_COUNTER_IMPORT_ROWS: (importId: string) => `/api/v1/metrics/counter-imports/${importId}/rows`,
    START_METRICS_COUNTER_IMPORT_CREATE_MISSING: (importId: string) => `/api/v1/metrics/counter-imports/${importId}/create-missing`,
    CREATE_METRICS_COUNTER_IMPORT_ROW: (importId: string, rowId: number) => `/api/v1/metrics/counter-imports/${importId}/rows/${rowId}/create`,
    GET_METRICS_STATISTICS: "/api/v1/metrics/statistics",
    GET_METRICS_GOALS: "/api/v1/metrics/goals",
  },
  REGISTRARS: {
    GET_REGISTRAR_PROFILES: "/api/v1/registrars/profiles",
    SYNC_REGISTRAR_DOMAINS: "/api/v1/registrars/registrar-domains/sync",
    GET_REGISTRAR_DOMAINS: "/api/v1/registrars/registrar-domains",
    GET_REGISTRAR_DOMAIN_OPTIONS: "/api/v1/registrars/registrar-domains/options",
    GET_REGISTRAR_DNS_RECORDS: "/api/v1/registrars/dns/records",
    CREATE_REGISTRAR_A_RECORD: "/api/v1/registrars/dns/a-records",
    CREATE_REGISTRAR_TXT_RECORD: "/api/v1/registrars/dns/txt-records",
    CREATE_REGISTRAR_NS_RECORD: "/api/v1/registrars/dns/ns-records",
    GET_DNS_BULK_JOB_STATUS: (jobId: string) => `/api/v1/registrars/dns-bulk/jobs/${jobId}/status`,
    CREATE_DNS_BULK_IMPORT: "/api/v1/registrars/dns-bulk/imports",
    CREATE_DNS_BULK_RECORDS: "/api/v1/registrars/dns-bulk/records",
    GET_DNS_BULK_IMPORTS: "/api/v1/registrars/dns-bulk/imports",
    UPDATE_DNS_BULK_IMPORT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}`,
    DELETE_DNS_BULK_IMPORT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}`,
    GET_DNS_BULK_IMPORT_ROWS: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/rows`,
    GENERATE_DNS_BULK_IMPORT_A: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/generate-a`,
    GENERATE_DNS_BULK_IMPORT_TXT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/generate-txt`,
    GENERATE_DNS_BULK_IMPORT_NS: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/generate-ns`,
    CHECK_DNS_BULK_IMPORT_A: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/check-a`,
    CHECK_DNS_BULK_IMPORT_TXT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/check-txt`,
    CHECK_DNS_BULK_IMPORT_NS: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/check-ns`,
    GET_DOMAIN_MATRIX_JOB_STATUS: (jobId: string) => `/api/v1/registrars/domain-matrix/jobs/${jobId}/status`,
    CREATE_DOMAIN_MATRIX_IMPORT: "/api/v1/registrars/domain-matrix/imports",
    GET_DOMAIN_MATRIX_IMPORTS: "/api/v1/registrars/domain-matrix/imports",
    UPDATE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}`,
    DELETE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}`,
    GENERATE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/generate`,
    CHECK_DOMAIN_MATRIX_IMPORT_AVAILABILITY: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/check-availability`,
    PURCHASE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/purchase`,
    GET_DOMAIN_MATRIX_IMPORT_ROWS: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/rows`,
    REGENERATE_DOMAIN_MATRIX_ROW: (rowId: number) => `/api/v1/registrars/domain-matrix/rows/${rowId}/regenerate`,
    PURCHASE_DOMAIN_MATRIX_ROW: (rowId: number) => `/api/v1/registrars/domain-matrix/rows/${rowId}/purchase`,
  },
  WEBMASTER: {
    GET_WEBMASTER_PROFILES: "/api/v1/webmaster/profiles",
    SYNC_WEBMASTER_HOSTS: "/api/v1/webmaster/webmaster-hosts/sync",
    GET_WEBMASTER_HOSTS: "/api/v1/webmaster/webmaster-hosts",
    GET_WEBMASTER_HOST_OPTIONS: "/api/v1/webmaster/webmaster-hosts/options",
    CREATE_WEBMASTER_HOST: "/api/v1/webmaster/webmaster-hosts",
    VERIFY_WEBMASTER_HOST_DNS: "/api/v1/webmaster/webmaster-hosts/verify-dns",
    GET_WEBMASTER_HOST_IMPORT_JOB_STATUS: (jobId: string) => `/api/v1/webmaster/host-import-jobs/${jobId}/status`,
    CREATE_WEBMASTER_HOST_IMPORT: "/api/v1/webmaster/host-imports",
    GET_WEBMASTER_HOST_IMPORTS: "/api/v1/webmaster/host-imports",
    UPDATE_WEBMASTER_HOST_IMPORT: (importId: string) => `/api/v1/webmaster/host-imports/${importId}`,
    DELETE_WEBMASTER_HOST_IMPORT: (importId: string) => `/api/v1/webmaster/host-imports/${importId}`,
    GET_WEBMASTER_HOST_IMPORT_ROWS: (importId: string) => `/api/v1/webmaster/host-imports/${importId}/rows`,
    START_WEBMASTER_HOST_IMPORT_CHECK: (importId: string) => `/api/v1/webmaster/host-imports/${importId}/check`,
    START_WEBMASTER_HOST_IMPORT_ADD_MISSING: (importId: string) => `/api/v1/webmaster/host-imports/${importId}/add-missing`,
    CREATE_WEBMASTER_HOST_IMPORT_ROW: (importId: string, rowId: number) => `/api/v1/webmaster/host-imports/${importId}/rows/${rowId}/create`,
    GET_WEBMASTER_POPULAR_QUERIES: (hostId: string) => `/api/v1/webmaster/${hostId}/search-popular-queries`,
    GET_WEBMASTER_SEARCH_EVENTS_HISTORY: (hostId: string) => `/api/v1/webmaster/${hostId}/search-events-history`,
    GET_WEBMASTER_SEARCH_QUERIES_HISTORY: (hostId: string) => `/api/v1/webmaster/${hostId}/search-queries-history`,
  },
} as const;
