export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    REFRESH: "/api/v1/auth/refresh",
    LOGOUT: "/api/v1/auth/logout",
  },
  METRICS: {
    GET_METRICS_PROFILES: "/api/v1/metrics/profiles",
    SYNC_METRICS_COUNTERS: "/api/v1/metrics/metrics-counters/sync",
    GET_METRICS_COUNTERS: "/api/v1/metrics/metrics-counters",
    GET_METRICS_COUNTER_OPTIONS: "/api/v1/metrics/metrics-counters/options",
    CREATE_METRICS_COUNTER: "/api/v1/metrics/metrics-counters",
    GET_METRICS_STATISTICS: "/api/v1/metrics/statistics",
    GET_METRICS_GOALS: "/api/v1/metrics/goals",
  },
  REGISTRARS: {
    GET_REGISTRAR_PROFILES: "/api/v1/registrars/profiles",
    SYNC_REGISTRAR_DOMAINS: "/api/v1/registrars/registrar-domains/sync",
    GET_REGISTRAR_DOMAINS: "/api/v1/registrars/registrar-domains",
    GET_REGISTRAR_DOMAIN_OPTIONS: "/api/v1/registrars/registrar-domains/options",
    GET_REGISTRAR_DNS_RECORDS: "/api/v1/registrars/dns/records",
    CREATE_REGISTRAR_A_RECORD: "/api/v1/registrars/dns/a-records",
    CREATE_REGISTRAR_TXT_RECORD: "/api/v1/registrars/dns/txt-records",
    GET_DNS_BULK_JOB_STATUS: (jobId: string) => `/api/v1/registrars/dns-bulk/jobs/${jobId}/status`,
    CREATE_DNS_BULK_IMPORT: "/api/v1/registrars/dns-bulk/imports",
    GET_DNS_BULK_IMPORTS: "/api/v1/registrars/dns-bulk/imports",
    UPDATE_DNS_BULK_IMPORT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}`,
    DELETE_DNS_BULK_IMPORT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}`,
    GET_DNS_BULK_IMPORT_ROWS: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/rows`,
    GENERATE_DNS_BULK_IMPORT_A: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/generate-a`,
    GENERATE_DNS_BULK_IMPORT_TXT: (importId: string) => `/api/v1/registrars/dns-bulk/imports/${importId}/generate-txt`,
    CREATE_DNS_BULK_ROW_A: (rowId: number) => `/api/v1/registrars/dns-bulk/rows/${rowId}/create-a`,
    CREATE_DNS_BULK_ROW_TXT: (rowId: number) => `/api/v1/registrars/dns-bulk/rows/${rowId}/create-txt`,
    GET_DOMAIN_MATRIX_JOB_STATUS: (jobId: string) => `/api/v1/registrars/domain-matrix/jobs/${jobId}/status`,
    CREATE_DOMAIN_MATRIX_IMPORT: "/api/v1/registrars/domain-matrix/imports",
    GET_DOMAIN_MATRIX_IMPORTS: "/api/v1/registrars/domain-matrix/imports",
    UPDATE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}`,
    DELETE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}`,
    GENERATE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/generate`,
    PURCHASE_DOMAIN_MATRIX_IMPORT: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/purchase`,
    GET_DOMAIN_MATRIX_IMPORT_ROWS: (importId: string) => `/api/v1/registrars/domain-matrix/imports/${importId}/rows`,
    REGENERATE_DOMAIN_MATRIX_ROW: (rowId: number) => `/api/v1/registrars/domain-matrix/rows/${rowId}/regenerate`,
    PURCHASE_DOMAIN_MATRIX_ROW: (rowId: number) => `/api/v1/registrars/domain-matrix/rows/${rowId}/purchase`,
  },
  WEBMASTER: {
    GET_WEBMASTER_PROFILES: "/api/v1/webmaster/profiles",
    SYNC_WEBMASTER_HOSTS: "/api/v1/webmaster/webmaster-hosts/sync",
    GET_WEBMASTER_HOSTS: "/api/v1/webmaster/webmaster-hosts",
    GET_WEBMASTER_HOST_OPTIONS: "/api/v1/webmaster/webmaster-hosts/options",
    CREATE_WEBMASTER_HOST: "/api/v1/webmaster/webmaster-hosts",
    VERIFY_WEBMASTER_HOST_DNS: "/api/v1/webmaster/webmaster-hosts/verify-dns",
    GET_WEBMASTER_POPULAR_QUERIES: (hostId: string) => `/api/v1/webmaster/${hostId}/search-popular-queries`,
    GET_WEBMASTER_SEARCH_EVENTS_HISTORY: (hostId: string) => `/api/v1/webmaster/${hostId}/search-events-history`,
    GET_WEBMASTER_SEARCH_QUERIES_HISTORY: (hostId: string) => `/api/v1/webmaster/${hostId}/search-queries-history`,
  },
} as const;
