export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    REFRESH: "/api/v1/auth/refresh",
    LOGOUT: "/api/v1/auth/logout",
  },
  METRICS: {
    GET_METRICS_PROFILES: "/api/v1/metrics/profiles",
    SYNC_METRICS_COUNTERS: "/api/v1/metrics/metrics-counters/sync",
    GET_METRICS_COUNTERS: "/api/v1/metrics/metrics-counters",
    GET_METRICS_COUNTER_OPTIONS: "/api/v1/metrics/metrics-counters/options",
    CREATE_METRICS_COUNTER: "/api/v1/metrics/metrics-counters",
    GET_METRICS_STATISTICS: "/api/v1/metrics/statistics",
    GET_METRICS_GOALS: "/api/v1/metrics/goals",
  },
  REGISTRARS: {
    GET_REGISTRAR_PROFILES: "/api/v1/registrars/profiles",
    SYNC_REGISTRAR_DOMAINS: "/api/v1/registrars/registrar-domains/sync",
    GET_REGISTRAR_DOMAINS: "/api/v1/registrars/registrar-domains",
    GET_REGISTRAR_DOMAIN_OPTIONS: "/api/v1/registrars/registrar-domains/options",
    GET_REGISTRAR_DNS_RECORDS: "/api/v1/registrars/dns/records",
    CREATE_REGISTRAR_A_RECORD: "/api/v1/registrars/dns/a-records",
    CREATE_REGISTRAR_TXT_RECORD: "/api/v1/registrars/dns/txt-records",
  },
  WEBMASTER: {
    GET_WEBMASTER_PROFILES: "/api/v1/webmaster/profiles",
    SYNC_WEBMASTER_HOSTS: "/api/v1/webmaster/webmaster-hosts/sync",
    GET_WEBMASTER_HOSTS: "/api/v1/webmaster/webmaster-hosts",
    GET_WEBMASTER_HOST_OPTIONS: "/api/v1/webmaster/webmaster-hosts/options",
    CREATE_WEBMASTER_HOST: "/api/v1/webmaster/webmaster-hosts",
    VERIFY_WEBMASTER_HOST_DNS: "/api/v1/webmaster/webmaster-hosts/verify-dns",
    GET_WEBMASTER_POPULAR_QUERIES: (hostId: string) => `/api/v1/webmaster/${hostId}/search-popular-queries`,
    GET_WEBMASTER_SEARCH_EVENTS_HISTORY: (hostId: string) => `/api/v1/webmaster/${hostId}/search-events-history`,
    GET_WEBMASTER_SEARCH_QUERIES_HISTORY: (hostId: string) => `/api/v1/webmaster/${hostId}/search-queries-history`,
  },
} as const;
