export const FIELD_LABELS: Record<string, string> = {
  country: "Страна",
  e_mail: "Email",
  o_email: "Email (организация)",
  person: "Имя (лат.)",
  person_r: "Имя",
  o_first_name: "Имя (орг.)",
  o_last_name: "Фамилия (орг.)",
  phone: "Телефон",
  o_phone: "Телефон (орг.)",
  birth_date: "Дата рождения",
  descr: "Описание",
  p_addr: "Почтовый адрес",
  o_addr: "Адрес (орг.)",
  passport: "Паспорт",
  private_person_flag: "Частное лицо",
  id_state: "Статус ID",
  o_company: "Компания",
  o_city: "Город (орг.)",
  o_postcode: "Индекс (орг.)",
  o_country_code: "Код страны (орг.)",
  o_fax: "Факс (орг.)",
  login: "Логин",
  passwd: "Пароль",
  server_ip: "IP сервера",
  title: "Заголовок",
  content: "Контент",
  counter_html_code: "HTML счетчиков",
  template_name: "Шаблон",
  html_title: "HTML Title",
  html_description: "HTML Description",
  html_keywords: "HTML Keywords",
  opt_user_contacts: "Блок контактов администратора",
  opt_feedback_link: "Ссылка на связь с администратором",
  opt_domain_shop_link: "Ссылка на лот в магазине доменов",
  opt_whois_link: "Ссылка на историю Whois",
  opt_se_link: "Ссылки на домен в поисковиках",
  opt_indexed_link: "Ссылки на индексированные страницы",
  opt_blogs_link: "Ссылки на упоминания в блогах",
  hosting: "Хостинг",
  web_forwarding: "Веб-перенаправления",
  parking: "Парковка",
  nss: "NS серверы",
  listFields: "Данные списка",
};
